<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: presale.proto

namespace Presales;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Presales.PresalesAddData</code>
 */
class PresalesAddData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     */
    protected $firstname = '';
    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     */
    protected $lastname = '';
    /**
     * Generated from protobuf field <code>string company = 3;</code>
     */
    protected $company = '';
    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     */
    protected $brandname = '';
    /**
     * Generated from protobuf field <code>string categoryid = 5;</code>
     */
    protected $categoryid = '';
    /**
     * Generated from protobuf field <code>string subcategoryid = 6;</code>
     */
    protected $subcategoryid = '';
    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     */
    protected $emailaddress = '';
    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     */
    protected $phone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $firstname
     *     @type string $lastname
     *     @type string $company
     *     @type string $brandname
     *     @type string $categoryid
     *     @type string $subcategoryid
     *     @type string $emailaddress
     *     @type string $phone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Presale::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstname($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastname($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company = 3;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Generated from protobuf field <code>string company = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     * @return string
     */
    public function getBrandname()
    {
        return $this->brandname;
    }

    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandname($var)
    {
        GPBUtil::checkString($var, True);
        $this->brandname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string categoryid = 5;</code>
     * @return string
     */
    public function getCategoryid()
    {
        return $this->categoryid;
    }

    /**
     * Generated from protobuf field <code>string categoryid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->categoryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 6;</code>
     * @return string
     */
    public function getSubcategoryid()
    {
        return $this->subcategoryid;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSubcategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->subcategoryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     * @return string
     */
    public function getEmailaddress()
    {
        return $this->emailaddress;
    }

    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->emailaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

}

