<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: presale.proto

namespace Presales;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Presales.PresalesAddList</code>
 */
class PresalesAddList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     */
    protected $firstname = '';
    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     */
    protected $lastname = '';
    /**
     * Generated from protobuf field <code>string company = 3;</code>
     */
    protected $company = '';
    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     */
    protected $brandname = '';
    /**
     * Generated from protobuf field <code>string category = 5;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string subcategory = 6;</code>
     */
    protected $subcategory = '';
    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     */
    protected $emailaddress = '';
    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string code = 9;</code>
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $firstname
     *     @type string $lastname
     *     @type string $company
     *     @type string $brandname
     *     @type string $category
     *     @type string $subcategory
     *     @type string $emailaddress
     *     @type string $phone
     *     @type string $code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Presale::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Generated from protobuf field <code>string firstname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstname($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Generated from protobuf field <code>string lastname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastname($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company = 3;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Generated from protobuf field <code>string company = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     * @return string
     */
    public function getBrandname()
    {
        return $this->brandname;
    }

    /**
     * Generated from protobuf field <code>string brandname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandname($var)
    {
        GPBUtil::checkString($var, True);
        $this->brandname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 5;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subcategory = 6;</code>
     * @return string
     */
    public function getSubcategory()
    {
        return $this->subcategory;
    }

    /**
     * Generated from protobuf field <code>string subcategory = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSubcategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->subcategory = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     * @return string
     */
    public function getEmailaddress()
    {
        return $this->emailaddress;
    }

    /**
     * Generated from protobuf field <code>string emailaddress = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailaddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->emailaddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 9;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

}

